nft, doc: Document public functions and methods
networkplumbing/go-nft pull request #19
Opened 2021-06-28 11:54 UTC by EdDev

2021-06-28 13:51 UTC, qinqon requested changes
It gives a lot of detail on functions, I think the "Note: " prefix is not needed

Does it make sense to put some "package" documentation under `doc.go` go file at nft package?

2021-06-28 13:51 UTC, qinqon commented on nft/chain.go
> +// Note: Missing arguments will cause an error once the config is applied.
Maybe we can link to nftables man with requirement ?

Also the "Note: " prefix is not needed there is similar explanations below and they don't have a "Note: " wich make sense.

2021-06-28 13:51 UTC, qinqon commented on nft/chain.go
> +// Note: The chain must not contain any rules or be used as a jump target.
No need for "Note: " prefix

2021-06-28 13:51 UTC, qinqon commented on nft/config.go
> +// Note that calling FlushRuleset has affect only on the configuration and will take affect only
Do we use "Note: " here ? or we remove it totally ?

2021-06-28 13:52 UTC, EdDev commented on nft/chain.go
> +// Note: Missing arguments will cause an error once the config is applied.
You mean to drop the `note: ` prefix or the whole line?

2021-06-28 13:54 UTC, EdDev commented on nft/chain.go
> +// Note: Missing arguments will cause an error once the config is applied.
> Maybe we can link to nftables man with requirement ?

It is mentioned in #20

2021-06-29 06:34 UTC, EdDev reviewed
> It gives a lot of detail on functions, I think the "Note: " prefix is not needed

I removed all "Note" wording.

> Does it make sense to put some "package" documentation under doc.go go file at nft package?

Done.

2021-06-29 06:34 UTC, EdDev commented on nft/chain.go
> +// Note: The chain must not contain any rules or be used as a jump target.
Done

2021-06-29 06:34 UTC, EdDev commented on nft/chain.go
> +// Note: Missing arguments will cause an error once the config is applied.
I will add it to the package level in `doc.go` as you suggested.

2021-06-29 06:34 UTC, EdDev commented on nft/config.go
> +// Note that calling FlushRuleset has affect only on the configuration and will take affect only
Removed, done.

2021-06-29 07:21 UTC, qinqon approved these changes

2021-06-29 07:23 UTC, merged