documentation: Update README and add CoC & CONTRIBUTING
networkplumbing/go-nft pull request #20
Opened 2021-06-28 13:27 UTC by EdDev

Content has been inspired by the following projects:
- https://github.com/containernetworking/plugins
- https://github.com/kubevirt/kubevirt

2021-06-28 13:29 UTC, phoracek requested changes

2021-06-28 13:29 UTC, phoracek commented on CODE_OF_CONDUCT.md
> +====================================
Please unify the formatting you use for headings

2021-06-28 13:29 UTC, phoracek commented on CODE_OF_CONDUCT.md
> +* Using welcoming and inclusive language
Please unify the formatting you use for bullet points

2021-06-28 13:29 UTC, phoracek commented on CONTRIBUTING.md
> +See https://chris.beams.io/posts/git-commit/
```suggestion
See https://chris.beams.io/posts/git-commit/.
```

2021-06-29 06:42 UTC, EdDev commented on CODE_OF_CONDUCT.md
> +====================================
Done

2021-06-29 06:42 UTC, EdDev commented on CODE_OF_CONDUCT.md
> +* Using welcoming and inclusive language
Done

2021-06-29 06:42 UTC, EdDev commented on CONTRIBUTING.md
> +See https://chris.beams.io/posts/git-commit/
Done

2021-06-29 07:32 UTC, qinqon requested changes
Add a reference to the godoc https://pkg.go.dev/github.com/eddev/go-nft

2021-06-29 07:49 UTC, qinqon approved these changes

2021-06-29 08:46 UTC, merged