schema, rule: Add NAT statements
networkplumbing/go-nft pull request #30
Opened 2021-07-25 06:25 UTC by EdDev

Allow users to define an NAT statements: dnat, snat, masquerade,
redirect.

Masquerade and redirect statements are (also) supported without any value.
In order to support defining multiple ports as a list, expressions now
support also an array/slice type.

2021-07-26 14:15 UTC, qinqon requested changes
First, pass unit tests pending review

2021-07-26 14:15 UTC, qinqon commented on automation/run-tests.sh
> +    sudo modprobe nft_masq
We can mount "/lib/modules" at the container so nftables can mount the modules

2021-07-26 14:15 UTC, qinqon commented on nft/rule_test.go
> +}
We use a table test here.

2021-07-26 14:15 UTC, qinqon commented on nft/rule_test.go
> +	statements, serializedStatements := createStatements()
This is duplicatd a both test fucntions, we can create a "buildFoo" helper for this.

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +	Flags []string `json:"-"`
We should make a Flag type to limit the cases where users can add garbage here (I know makeing a type is not totally preventing but at least is better than directly expose string).

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +
Let's Create a type NATFlag

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +		dynamicStructure[redirect] = nil
This is complex enough to conert the swtich into an if statement I would say.

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +	}
What do you think of 
```golang
if s.Masquerade == nil {
    _, masqueradeDefined := dynamicStructure[masquerade]
   s.Masquerade = &Masquearde{Enabled: masqueradeDefined}
}
```

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +	}
similar comment as masquerade

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +		}
If we are at this "case" is already verified that data is a interface slice and we don't need to dothe Unmarshal to check it.

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +}
This is not very golang idiomatic apart from the fact that we can skip one Marshal case, what do you think about:

```golang
flagCount == len(f.Flags)
if flagCount == 0 {
    return []byte{}
}
if flagCount == 1 {
    return json.Marshal(f.Flags[0])
}
return json.Marshal(f.Flags)
```

2021-07-26 14:15 UTC, qinqon commented on nft/schema/rule.go
> +		return fmt.Errorf("flags values require string type: %T(%v)", dynamicStruct, dynamicStruct)
You don't need to "cast" it again the switch statement can return the value already

```suggestion
	switch v := dynamicStruct.(type) {
	case string:
		f.Flags = []string{v}
	case []interface{}:
		for _, val := range v {
			stringVal, ok := val.(string)
			if !ok {
				return fmt.Errorf("flags values require string type: %T(%v)", dynamicStruct, dynamicStruct)
			}
			f.Flags = append(f.Flags, stringVal)
		}
	default:
		return fmt.Errorf("flags values require string type: %T(%v)", dynamicStruct, dynamicStruct)
```

2021-08-01 18:48 UTC, EdDev reviewed
Thank you for the thorough review!

2021-08-01 18:48 UTC, EdDev commented on nft/rule_test.go
> +}
Good point, thanks! Done.

2021-08-01 18:48 UTC, EdDev commented on nft/rule_test.go
> +	statements, serializedStatements := createStatements()
It looks the same indeed, but the variables are in use. Having a helper that returns 4 values seems ugly and artificial to me. No logic is repeated here, so I think we are safe.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +	Flags []string `json:"-"`
At the moment we are not enforcing such limitations under the `schema` sub-package, only at the `nft` level.
My main reason to be a bit loose at this is:
- It is enforced by the libnftables library, therefore corrupted configuration will not really reach the system.
- It leaves space for additions that are added to libnftables/nft, to be uable to users by using the `schema` directly. If we use a type, we will be forced to add it to `go-nft` before anyone can use it.

Considering other such fields do not use types for restrictions, I prefer to leave this loose as well.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +
See prev answer.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +		dynamicStructure[redirect] = nil
Sorry, I do not understand your comment here. What are you suggesting exactly?
If you meant to drop the `switch` and use an `if`, I see no benefit.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +	}
This is possible, but it seems to be inconsistent with the interpretation pattern used by `json`.
When `masquerade` is not mentioned at all, due to its definition as a pointer, it should result in `nil`. But if we take this suggestion, it will not be `nil` and a user will have to query the `Enabled` and the other fields to see if it is relevant or not.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +	}
See previous answer

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +		}
Yes, seems to be a leftover.
Done.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +}
1. In any language, I think it is safer to have a single exit point when possible.
2. I think a `switch` is a better fit when the condition is on the same value twice or more.
3. Just not needing to ask the question if it is ok to return with a `nil` or and empty byte slice is rewarding to me.

2021-08-01 18:48 UTC, EdDev commented on nft/schema/rule.go
> +		return fmt.Errorf("flags values require string type: %T(%v)", dynamicStruct, dynamicStruct)
Nice, I did not know this language feature. Thanks!
Done

2021-08-01 18:48 UTC, EdDev commented on automation/run-tests.sh
> +    sudo modprobe nft_masq
I tried it, but it did not work for me locally.
It may be related to other permissions (CAP , Labeling), but I have not found the formula.

It is also not that bad, this way we have better control and are unlikely to damage the host (having ability to (un)load kmod/s in the container is pretty risky).

2021-08-01 18:51 UTC, EdDev commented
change: Responding to the review.

2021-08-03 12:09 UTC, qinqon commented on nft/schema/rule.go
> +		dynamicStructure[redirect] = nil
Can be done at follow up and it's not that important.

2021-08-03 12:11 UTC, qinqon approved these changes

2021-08-03 14:04 UTC, EdDev commented
change: Rebase

2021-08-03 14:06 UTC, merged