tests: Reorganize structure of the integration tests
networkplumbing/go-nft pull request #31
Opened 2021-07-25 13:55 UTC by EdDev

Create a testlib sub-package for test helpers and an example sub-package
for example tests.
Place the current no-mac-spoofing example in its own well named test
file.

Future examples are expected to be placed under the `example`
sub-package with a dedicated test file name.

2021-07-26 10:13 UTC, qinqon requested changes
What about importing testlib with "." ?

2021-07-26 10:13 UTC, qinqon commented on tests/example/nomacspoofing_test.go
> +	"github.com/networkplumbing/go-nft/tests/testlib"
For this specific case maybe it's worth it to import it with "."

2021-08-01 16:01 UTC, EdDev commented on tests/example/nomacspoofing_test.go
> +	"github.com/networkplumbing/go-nft/tests/testlib"
I think it is a bad practice overall. Eliminating a namespace is always bad, it gives it a context.

2021-08-03 12:12 UTC, qinqon approved these changes

2021-08-03 13:58 UTC, merged