exec: Use a temp file to pass data to the `nft` binary
networkplumbing/go-nft pull request #35
Opened 2021-09-12 07:03 UTC by EdDev

Using a buffer to pass the nftables configuration to `stdin` has been
unintentionally blocked by one of the latest SELinux policies [1].

While the policy issue is fixed, this change introduces an alternative
way to pass the configuration data using a temporary file.

The workaround can be removed once the SELinux policy is fixed.

[1] https://github.com/containers/container-selinux/issues/147

2021-09-12 12:13 UTC, AlonaKaplan commented on nft/exec/exec.go
> +	tmpFile, err := ioutil.TempFile(os.TempDir(), "spoofcheck-")
Where is the code using this `tmpFile`?

2021-09-12 13:08 UTC, EdDev commented on nft/exec/exec.go
> +	tmpFile, err := ioutil.TempFile(os.TempDir(), "spoofcheck-")
A bad bug.
I need to make sure we cover well the `exec` as well in the integration tests.

2021-09-13 05:23 UTC, qinqon requested changes
I think it's better moving the tmp file generation at exec function.

2021-09-13 05:23 UTC, qinqon commented on nft/exec/exec.go
> +	if err := tmpFile.Close(); err != nil {
We are removing at defer, I think we don't need to close it, but if we needed let's do it at defer next to remove.

2021-09-13 05:23 UTC, qinqon commented on nft/exec/exec.go
> +func execCommand(args ...string) (*bytes.Buffer, error) {
Why don't we generate the tmpFile here so we don't have to touch RaeadConfig ? At the end is a implementation detail of how do we exec and since it's a temporal solution we are going back using stdin soon.

2021-09-13 05:30 UTC, qinqon requested changes

2021-09-13 05:30 UTC, qinqon commented on nft/exec/exec.go
> +	defer os.Remove(tmpFile.Name())
You are removing the tmp file but not the tmp dir, maybe we want to skip the tmpDir generation.

2021-09-13 07:35 UTC, EdDev commented on nft/exec/exec.go
> +	tmpFile, err := ioutil.TempFile(os.TempDir(), "spoofcheck-")
Done.
It was a false-negative which was fixed (PR merged already).

2021-09-13 07:35 UTC, EdDev commented on nft/exec/exec.go
> +	defer os.Remove(tmpFile.Name())
No one is creating the tempDir. It just returns the OS default one.

2021-09-13 07:35 UTC, EdDev commented on nft/exec/exec.go
> +func execCommand(args ...string) (*bytes.Buffer, error) {
Because this function just executes the command and no longer needs stdin and its conversions.
Once the fix is in place, we will probably wait a few months and then just revert this commit.

2021-09-13 07:35 UTC, EdDev commented on nft/exec/exec.go
> +	if err := tmpFile.Close(); err != nil {
This is the formal example: https://pkg.go.dev/io/ioutil#example-TempFile

Per my understanding, `Close` is closing the FD, while `Remove` is removing the file (on disk).
I do not think you can remove an used file.

If we place the `Close` in the defer, we will have to handle its error somehow (and use named return params). Is there a real problem you see with this as it is now that merits this?

2021-09-13 07:54 UTC, qinqon commented on nft/exec/exec.go
> +	defer os.Remove(tmpFile.Name())
Ahh right.

2021-09-13 07:54 UTC, qinqon approved these changes

2021-09-13 08:06 UTC, merged