tests, testlib: Assure nftables cleanup
networkplumbing/go-nft pull request #44
Opened 2023-02-15 12:04 UTC by EdDev

In case asserts fail or there is an unexpected panic in the tests, the cleanup (flush) of the existing nftables should still be executed.

This change assures the cleanup execution by using `defer`.

2023-02-15 12:13 UTC, qinqon requested changes
The golang test framework support Cleanup, here is an example 
```golang
func setup(t *testing.T) {
	mStore = &store.MockStore{DB: "some_connection"}
	t.Cleanup(tearDown)
}

func tearDown() {
	mStore.Reset()
}

func Test_Add(t *testing.T) {
	setup(t)
	mStore.Add("some data")

	expected := 1
	got := mStore.Count()
	if expected != got {
		t.Fatalf("expected: %d items, got: %d items", expected, got)
	}
}
```

2023-02-15 12:27 UTC, EdDev commented
> The golang test framework support Cleanup

Nice.
For this I need a wider change, touching all existing tests.

I'll look into it.

2023-02-22 08:14 UTC, EdDev commented
@qinqon , I changed it to use `Cleanup` per your suggestion. Thanks!

2023-02-22 12:39 UTC, qinqon approved these changes

2023-02-22 13:05 UTC, merged