nft: Basic operations
networkplumbing/go-nft pull request #6
Opened 2021-05-31 11:25 UTC by EdDev

2021-05-31 14:13 UTC, qinqon commented
I will try to add a pair of comments for the API

2021-06-03 11:23 UTC, qinqon requested changes
Reviewed example_test.go to check the API TL;DR some factory functions can make it less verbose.

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +	config.AddTable(table)
Some syntactic sugar will make this less verbose
```golang
table := config.AddTable("example", nft.FamilyBRIDGE)
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +	config.AddChain(baseChain)
Same here
```golang
chainType, chainHook, chainPrio, chainPolicy := nft.TypeFilter, nft.HookPreRouting, -300, nft.PolicyAccept
config.AddChain(able, baseChainName, &chainType, &chainHook, &chainPrio, &chainPolicy)
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +	config.AddChain(macChain)
```golang
ifaceChain := config.AddRegularChain(table, ifaceChainName)
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +		{Verdict: schema.Verdict{Jump: &schema.ToTarget{Target: ifaceChainName}}},
Add some factory functions to simplify `Match` field.

```golang
Match: nft.Equal(nft.RawData(`{"meta":{"key":"iifname"}}`, nft.String(&ifaceName))
```

Similar for Verdict
```golang
Verdict: nft.Jump(nft.ToTarget(ifaceChainName))
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +		{Verdict: schema.Verdict{SimpleVerdict: schema.SimpleVerdict{Return: true}}},
Here it would be something like 

```golang
Match: nft.Equal(nft.Payload(PayloadProtocolEther, PayloadFieldEtherSAddr), nft.String(&macAddress))
```

And verdict
```golang
Verdict: nft.Return(true)
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +	}
```golang
Verdict: Drop(true)
```

Also if nftable SimpleVeredict is either Drop or Return we can just create `Drop()` and `Return()` they will set flags according to that.

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +			Family: schema.FamilyBRIDGE,
Allthouigh the value is all capital "BRIDGE" I would say that as user interface we name stuff like `FamilyBRIDGE` similar to the others `FamilyBridge` or even add a package for family and we do `family.Bridge`

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +					Left:  schema.Expression{RowData: []byte(`{"meta":{"key":"iifname"}}`)},
I think we have to cal `RawData` `Json` and pass a string, the conversion to []byte can be done at the implementation so it's less verbose and is clear from user perspective that it has to be a json.

```golang
Left:  schema.Expression{Json: `{"meta":{"key":"iifname"}}`},
```

2021-06-03 11:23 UTC, qinqon commented on tests/example_test.go
> +					Right: schema.Expression{String: &ifaceName},
A problem with `Expression` is that the users can set multiple fields and that's forbidden, one possible fix for that is to not export the `Expression` fields and use some exported factory functions to create them propertly
```golang
type Expression {
    str * string
    integer * int
}

func StringExpression(value string) Expression {
    return Expression{str: value}
}
```

Then we can use Expression as receiver and do some accessors to read them

```golang
func (e Expression) String() *string {
   return e.str
}
```


```

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +	config.AddTable(table)
I answered on the [other](https://github.com/EdDev/go-nft/pull/6/commits/dd0b70dcc29bca8724fe7704225408a4932c46b0#r644689985) comment.

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +	config.AddChain(baseChain)
As I see it, the creation and operation with it (add, delete, flush, etc..) are two different things.
I am looking for consistency here, and it is easy to have consistency when each part has a single responsibility.

If one is looking for a minimalist approach, the `New*` can be inlined: `config.AddChain(NewChain(...))`.
Or, just compose the whole config directly.

BTW, by splitting the two, you allow the user to define a base config (template) and then just copy-change it. I find this flexibility more attractive with a (very) low cost. It also served well the unit tests.

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +		{Verdict: schema.Verdict{Jump: &schema.ToTarget{Target: ifaceChainName}}},
The verdict one is pretty easy to implement, but the match one is a bit more challenging.
As no factory has been introduced at this level (for statements and expressions), I will add them after the basic part gets in.

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +		{Verdict: schema.Verdict{SimpleVerdict: schema.SimpleVerdict{Return: true}}},
I responded about this in general earlier, but I just want to point out that having `Equal(Payload(..)...)` and `Equal(RawData(..)..)` is not that straight forward and will require logic I am not sure is worth it.
But again, it belongs to later PR/s after the base is in place.

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +	}
Ack.
I opened an [issue](https://github.com/EdDev/go-nft/issues/9) to track this, so we will not forget to add it.

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +			Family: schema.FamilyBRIDGE,
The only reason the bridge is all capital is due to the other families having the same format (as they use short names).
I really do not mind, so if it bothers you, it may bother others... I am changing it.

Done

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +					Left:  schema.Expression{RowData: []byte(`{"meta":{"key":"iifname"}}`)},
I have already bad experience with Python when handling strings, unicode and bytes, especially from io.
With json marshaling and unmarhsaling, bytes are used and not strings, so I prefer to be consistent here as well.

The "verbose" part is the addition of `[]byte()`?

2021-06-06 11:35 UTC, EdDev commented on tests/example_test.go
> +					Right: schema.Expression{String: &ifaceName},
This is true at multiple layers of the schema, the expression is only one case.

I am not in favor of complicating this too much, as it will require wrapping many parts with helpers and the added value is questionable: Having many helpers requires users to know them all, which may be exhausting.

I would prefer to add a validation step to the config (e.g. `config.Validate()`), checking and reporting proper errors if something is incorrectly set. But this seems like a large investment and I hope to see this added gradually per user experience.

2021-06-07 05:19 UTC, qinqon commented on tests/example_test.go
> +		{Verdict: schema.Verdict{Jump: &schema.ToTarget{Target: ifaceChainName}}},
Can you add something at the PR description with possible follow up PRs ? Since this is a from scratch stuff not all will be done here.

2021-06-07 05:24 UTC, qinqon commented on tests/example_test.go
> +					Left:  schema.Expression{RowData: []byte(`{"meta":{"key":"iifname"}}`)},
I think we don't have that issue here, you are not limiting the user by exposing a string instead of []byte here.

And about the naming, `Json()` is clear for users since we are using notables with `-j` if in the future notables add something different like say yaml we will be able to add `Yaml()` function here but with `RawData()` is not clear.

2021-06-07 06:48 UTC, EdDev commented on tests/example_test.go
> +					Left:  schema.Expression{RowData: []byte(`{"meta":{"key":"iifname"}}`)},
The current encoder/decoder is using bytes in its API. We are providing a back-door to provide row data for expressions that have not been defined in the schema yet.
I think this is consistent with what "raw" means for the json (or others).
In general, accessing I/O is usually done using bytes and not strings, especially at the library level.

> Json() is clear for users since we are using notables with -j

I guess I can use `json.RawMessage()` if you think it is clearer.
But it will not be correct in reality, because this can also be a simple string, boolean or integer (e.g. []byte("0")).

IMO, passing a string that is then converted into a byte slice adds nothing here. As this is raw data, it makes sense to expect raw bytes, fitting with the was the json encoder/decoder works.

I will try to add a doctext to document what this "RawData" means.

2021-06-07 06:48 UTC, EdDev commented on tests/example_test.go
> +		{Verdict: schema.Verdict{Jump: &schema.ToTarget{Target: ifaceChainName}}},
Is #9 enough?

2021-06-07 08:56 UTC, qinqon commented on tests/example_test.go
> +	config.AddTable(table)
fair enoough

2021-06-07 08:57 UTC, qinqon commented on tests/example_test.go
> +		{Verdict: schema.Verdict{Jump: &schema.ToTarget{Target: ifaceChainName}}},
fair enoough

2021-06-07 08:57 UTC, qinqon commented on tests/example_test.go
> +					Left:  schema.Expression{RowData: []byte(`{"meta":{"key":"iifname"}}`)},
I suppose doctext is good enough thanks

2021-06-07 08:59 UTC, qinqon commented on tests/example_test.go
> +					Right: schema.Expression{String: &ifaceName},
Then we have to decide if we want to complicate the "Validate" or the "construction"

2021-06-08 13:44 UTC, EdDev commented
change: Rebase

2021-06-10 08:21 UTC, merged