Automation & CI
networkplumbing/go-nft pull request #8
Opened 2021-06-03 09:40 UTC by EdDev

Prepare the automation scripts and CI (github actions workflow).

Note: These changes have been extracted from #6 to ease the review.

2021-06-03 10:00 UTC, phoracek requested changes
Some nits.

I verified the unit test, it works fine.
Import formatting works fine.
Gofmt works fine.

2021-06-03 10:00 UTC, phoracek commented on .github/workflows/main.yml
> +    - name: UnitTest
You can use spaces! This is just a title

2021-06-03 10:00 UTC, phoracek commented on .github/workflows/main.yml
>        run: |
The title of this section is "build" despite all you do here is running checks and unit tests

2021-06-03 10:00 UTC, phoracek commented on .github/workflows/main.yml
> +        run: ./automation/run-tests.sh --itest
Could you save me some brain cycles and use unit-test and integration-test instead?

2021-06-03 10:00 UTC, phoracek commented on automation/go-format.sh
> +#!/usr/bin/env bash
You never use this script

2021-06-03 10:00 UTC, phoracek commented on automation/run-tests.sh
> +: "${CONTAINER_IMG:="golang:alpine"}"
This will default to use Docker Hub. That has a risk of hitting limit in the number of pulls. I'd advice to use quay

2021-06-03 10:00 UTC, phoracek commented on automation/run-tests.sh
> +        $USE_TTY \
Is there ever a reason to allocate a terminal?

2021-06-03 10:29 UTC, qinqon requested changes
It's weird to me that we don't have something at root level, but since it's pretty small I suppose we are ok, later on we can add something at root level and make `run-tests.sh` delegate on it.

2021-06-03 10:29 UTC, qinqon commented on .github/workflows/main.yml
> +        ./automation/run-tests.sh --fmt
Can you move `go get golang.org/x/tools/cmd/goimports` to run-tests.sh ?

2021-06-03 10:29 UTC, qinqon commented on automation/run-tests.sh
> +        unformatted=$(goimports -l --local "github.com/eddev/go-nft" ./nft ./tests)
You can get and run at the same command with `go run golang.org/x/tools/cmd/goimports -l --local "github.com/eddev/go-nft" ./nft ./tests`

2021-06-03 10:29 UTC, qinqon commented on automation/run-tests.sh
> +        -v "$PROJECT_PATH":"$CONTAINER_WORKSPACE":Z \
To do this I think you need to also set the gid and uid to mimic the host user/group also I remember it having issues with selinux.

2021-06-03 10:52 UTC, EdDev commented on automation/run-tests.sh
> +: "${CONTAINER_IMG:="golang:alpine"}"
I have not seen `golang` on quay and prefer not to mirror manually until I must.
Does that sound reasonable?

2021-06-03 10:52 UTC, EdDev commented on .github/workflows/main.yml
>        run: |
Well, it does build as well.
How would you suggest to call it?

2021-06-03 10:52 UTC, EdDev commented on .github/workflows/main.yml
> +        ./automation/run-tests.sh --fmt
But it is not needed there, it comes with the golang installation. Here it does not.

2021-06-03 10:52 UTC, EdDev commented on automation/go-format.sh
> +#!/usr/bin/env bash
It is for local usage, it is suppose to me mentioned in the commit message.

2021-06-03 10:52 UTC, EdDev commented on automation/run-tests.sh
> +        $USE_TTY \
Yes, for local runs.

2021-06-03 10:52 UTC, EdDev commented on automation/run-tests.sh
> +        -v "$PROJECT_PATH":"$CONTAINER_WORKSPACE":Z \
I do not think I understand. Maybe you can explain what you mean exactly. This worked for me locally as well.

2021-06-03 10:52 UTC, EdDev commented on automation/run-tests.sh
> +        unformatted=$(goimports -l --local "github.com/eddev/go-nft" ./nft ./tests)
I will check locally, but this seems to assume the binary points to this path. I do not know if it is ok to assume this.

2021-06-03 10:59 UTC, phoracek commented on .github/workflows/main.yml
>        run: |
Checks and unit tests? I don't have a particular suggestion, just pointing out it is inaccurate.

2021-06-03 11:01 UTC, phoracek commented on automation/run-tests.sh
> +: "${CONTAINER_IMG:="golang:alpine"}"
An alternative would be to create an account for this repo and use it while pulling.

If you keep this anonymous and under Docker Hub, you risk that one day your check will refuse to work.

2021-06-06 07:45 UTC, EdDev commented on automation/run-tests.sh
> +: "${CONTAINER_IMG:="golang:alpine"}"
You are suggesting to maintain a mirror, or if at it, an image for this. I intentionally prefer not to at this point, hoping to reduce the burden.

I think this is small enough at this stage not to require such a maintenance overhead, but if this will show as a problem, we can go ahead and do it.

2021-06-06 07:45 UTC, EdDev commented on .github/workflows/main.yml
> +    - name: UnitTest
Done

2021-06-06 07:45 UTC, EdDev commented on .github/workflows/main.yml
> +        ./automation/run-tests.sh --fmt
This relates to the comment [here](https://github.com/EdDev/go-nft/pull/8/commits/5f84a482d080efe9606261e3335dabbeeca6f703#r644674318). I will move it there as you suggested in that comment, thanks!

2021-06-06 07:45 UTC, EdDev commented on automation/run-tests.sh
> +        unformatted=$(goimports -l --local "github.com/eddev/go-nft" ./nft ./tests)
Thanks! Done.

2021-06-06 07:45 UTC, EdDev commented on .github/workflows/main.yml
> +        run: ./automation/run-tests.sh --itest
Done

2021-06-06 07:45 UTC, EdDev commented on automation/go-format.sh
> +#!/usr/bin/env bash
I updated the commit message.

2021-06-08 13:28 UTC, qinqon commented
/lgtm

2021-06-08 13:28 UTC, qinqon approved these changes

2021-06-08 13:43 UTC, merged